compatibility_date = "2021-08-27" # required
compatibility_flags = ["formdata_parser_supports_files"] # required                                           
name = "awesome-worker" 
type = "javascript" 
workers_dev = true 

[vars]
WORKERS_RS_VERSION = "0.0.4"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration

[durable_objects]
bindings = [
  {name = "COUNTER", class_name = "Counter"}, # the `class_name` uses the Rust struct identifier name
]
